import { ethers } from "ethers";
const p = new ethers.JsonRpcProvider("http://localhost:8547");
const t = async (label, fn) => { const s = Date.now(); try { const r = await fn(); console.log(label, (Date.now()-s)+"ms", typeof r === "object" ? "" : r); return r; } catch (e) { console.log(label, (Date.now()-s)+"ms", "ERROR:", e.shortMessage ?? e.message); } };
await t("blockNumber", () => p.getBlockNumber());
await t("getFeeData", async () => { const f = await p.getFeeData(); return `maxFee=${f.maxFeePerGas}`; });
await t("feeHistory", () => p.send("eth_feeHistory", ["0x5", "latest", [10, 50, 90]]));
const w = new ethers.Wallet("0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80", p);
await t("setBalance", () => p.send("anvil_setBalance", [w.address, "0x8ac7230489e80000"]));
await t("getNonce", () => p.getTransactionCount(w.address));
await t("estimateGas", () => p.estimateGas({ from: w.address, to: w.address, value: 1n }));
const tx = await t("sendTransaction", () => w.sendTransaction({ to: w.address, value: 1n }));
await t("wait(receipt)", () => tx.wait());
const tx2 = await t("sendTx2", () => w.sendTransaction({ to: w.address, value: 2n }));
await t("wait(receipt2)", () => tx2.wait());
