import { withSentryConfig } from "@sentry/nextjs";
import type { NextConfig } from "next";
import { withWorkflow } from "workflow/next";
import { CLI_VERSION_HEADER_RULE } from "./lib/cli-version";

const nextConfig = {
  output: "standalone",
  // Admin test routes (app/api/admin/test/**/route.staging.ts) are excluded
  // from the prod bundle by omitting "staging.ts" from pageExtensions. See
  // KEEP-237. Staging/PR builds set INCLUDE_TEST_ENDPOINTS=true via the build
  // workflow to compile them in.
  // "js"/"jsx" must remain so that the workflow runtime routes generated by
  // withWorkflow at app/.well-known/workflow/v1/{flow,step,webhook}/route.js
  // are picked up by the Next.js router; without them the in-pod graphile
  // worker POSTs return Next's HTML 404 and every workflow run fails.
  pageExtensions:
    process.env.INCLUDE_TEST_ENDPOINTS === "true"
      ? ["ts", "tsx", "js", "jsx", "staging.ts", "staging.tsx"]
      : ["ts", "tsx", "js", "jsx"],
  // Bake INCLUDE_TEST_ENDPOINTS so lib/admin-auth.ts and lib/auth.ts can
  // gate runtime behavior (admin routes, rate-limit bypass) on the build-
  // time flag. The bundler (Turbopack / webpack) replaces
  // `process.env.INCLUDE_TEST_ENDPOINTS` with the literal captured here, so
  // runtime env cannot override the baked value.
  //
  // NOTE: `env` config inlines into BOTH server and client bundles. The
  // value ("true" or "") is a non-sensitive feature flag, so this is fine.
  // Never put secrets in this block.
  //
  // See KEEP-237.
  env: {
    INCLUDE_TEST_ENDPOINTS: process.env.INCLUDE_TEST_ENDPOINTS ?? "",
  },
  // Full transitive dependency tree of @workflow/world-postgres, kept out of
  // the bundler. These are server-only and several resist bundling outright:
  // cbor-extract loads prebuilt .node binaries through
  // node-gyp-build-optional-packages, and pg/graphile-worker expect a real
  // node_modules at runtime.
  //
  // Being external means the file tracer, not the bundler, is responsible for
  // delivering them into .next/standalone. That used to be impossible: the SDK
  // reached the package via require(process.env.WORKFLOW_TARGET_WORLD), a
  // computed specifier nothing can follow statically, so the whole tree had to
  // be force-included by hand below and hoisted out of pnpm's .pnpm/ store in
  // .npmrc for the globs to match. instrumentation.ts now imports the package
  // by literal specifier and injects it with setWorld(), so the tracer follows
  // the import chain and resolves the tree through .pnpm/ on its own.
  //
  // Regenerate with: tsx scripts/list-world-deps.ts
  serverExternalPackages: [
    "ioredis",
    "@babel/code-frame",
    "@babel/helper-validator-identifier",
    "@cbor-extract/cbor-extract-darwin-arm64",
    "@cbor-extract/cbor-extract-darwin-x64",
    "@cbor-extract/cbor-extract-linux-arm",
    "@cbor-extract/cbor-extract-linux-arm64",
    "@cbor-extract/cbor-extract-linux-x64",
    "@cbor-extract/cbor-extract-win32-x64",
    "@graphile/logger",
    "@types/debug",
    "@types/interpret",
    "@types/ms",
    "@types/node",
    "@types/pg",
    "@types/semver",
    "@vercel/oidc",
    "@vercel/queue",
    "@workflow/errors",
    "@workflow/utils",
    "@workflow/world",
    "@workflow/world-local",
    "@workflow/world-postgres",
    "ansi-regex",
    "ansi-styles",
    "argparse",
    "async-sema",
    "balanced-match",
    "brace-expansion",
    "callsites",
    "cbor-extract",
    "cbor-x",
    "chalk",
    "cliui",
    "color-convert",
    "color-name",
    "cosmiconfig",
    "cron-parser",
    "debug",
    "detect-libc",
    "dotenv",
    "drizzle-orm",
    "emoji-regex",
    "error-ex",
    "escalade",
    "get-caller-file",
    "graphile-config",
    "graphile-worker",
    "has-flag",
    "import-fresh",
    "interpret",
    "is-arrayish",
    "is-fullwidth-code-point",
    "js-tokens",
    "js-yaml",
    "json-parse-even-better-errors",
    "json5",
    "lines-and-columns",
    "minimatch",
    "mixpart",
    "ms",
    "node-gyp-build-optional-packages",
    "parent-module",
    "parse-json",
    "path-type",
    "pg",
    "pg-cloudflare",
    "pg-connection-string",
    "pg-int8",
    "pg-pool",
    "pg-protocol",
    "pg-types",
    "pgpass",
    "picocolors",
    "postgres",
    "postgres-array",
    "postgres-bytea",
    "postgres-date",
    "postgres-interval",
    "require-directory",
    "resolve-from",
    "semver",
    "split2",
    "string-width",
    "strip-ansi",
    "supports-color",
    "tslib",
    "ulid",
    "undici",
    "undici-types",
    "wrap-ansi",
    "xtend",
    "y18n",
    "yargs",
    "yargs-parser",
    "zod",
  ],
  // The standalone server.js emitted by `output: "standalone"` does a bare
  // `require('next')`, which needs next/package.json to resolve. Next's tracer
  // only catches that bare specifier when some other file in the bundle also
  // imports next directly. In prod builds INCLUDE_TEST_ENDPOINTS is empty, the
  // staging-only `*.staging.ts` files that triggered the side-effect are
  // excluded, and the standalone output ends up with next/dist/ but no
  // next/package.json - runtime crashes with "Cannot find module 'next'" on
  // server.js line 16. Next's tracer also does not follow next's own runtime
  // dependencies through pnpm's .pnpm/ store, so the set listed in
  // next/package.json `dependencies` plus the architecture-specific @next/swc
  // binary used on Alpine (musl) are force-included alongside it. The .npmrc
  // public-hoist-pattern entries hoist these to top-level node_modules/ so the
  // literal globs below can match them.
  //
  // The @workflow/world-postgres tree used to be listed here too. It no longer
  // needs to be: instrumentation.ts imports the package by literal specifier
  // and injects it with setWorld(), so the tracer follows the import chain and
  // pulls the tree in on its own.
  outputFileTracingIncludes: {
    "/*": [
      "./node_modules/next/**/*",
      "./node_modules/@next/env/**/*",
      "./node_modules/@next/swc-linux-x64-musl/**/*",
      "./node_modules/@swc/helpers/**/*",
      "./node_modules/baseline-browser-mapping/**/*",
      "./node_modules/caniuse-lite/**/*",
      "./node_modules/postcss/**/*",
      "./node_modules/styled-jsx/**/*",
      "./node_modules/next/dist/compiled/@vercel/og/**/*",
    ],
  },
  logging: {
    fetches: {
      fullUrl: true,
    },
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "raw.githubusercontent.com",
        pathname: "/trustwallet/assets/**",
      },
    ],
  },
  async rewrites() {
    return [{ source: "/openapi.json", destination: "/api/openapi" }];
  },
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          { key: "X-Frame-Options", value: "DENY" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          {
            key: "Strict-Transport-Security",
            value: "max-age=63072000; includeSubDomains",
          },
        ],
      },
      // The kh CLI already checks this header on every response and warns when
      // its own build is older (internal/http/version.go). The client half
      // shipped long ago; nothing was ever sending the header, so the check was
      // inert. Updates are manual (`kh update`) with no prompt, so this warning
      // is the only signal an out-of-date CLI ever gets.
      CLI_VERSION_HEADER_RULE,
    ];
  },
  async redirects() {
    // Points agent crawlers at the docs. DOCS_BASE_URL lets a deployment send
    // them to its own docs, or drop the redirect entirely by setting the
    // variable empty - otherwise every deployment permanently redirects its own
    // /llms.txt to a host KeeperHub runs. Read at build time like the rest of
    // this file, so it is set for the image build rather than at runtime.
    const docsBaseUrl =
      process.env.DOCS_BASE_URL ?? "https://docs.keeperhub.com";
    if (!docsBaseUrl) {
      return [];
    }
    return [
      {
        source: "/llms.txt",
        destination: `${docsBaseUrl}/llms.txt`,
        permanent: true,
      },
    ];
  },
} satisfies NextConfig & { eslint?: { ignoreDuringBuilds?: boolean } };

const { SENTRY_ORG, SENTRY_PROJECT, SENTRY_RELEASE } = process.env;

// Enable the workflow DevKit's deferred builder to avoid the eager
// builder's per-route esbuild scan of every "use step" file. The eager
// scan + intermediate bundle takes 2-5 min on first hit per route in
// dev, making /api/workflow/* effectively unusable on a normal laptop.
// The deferred builder uses socket-driven lazy discovery and only
// pre-bundles the well-known /flow, /step, /webhook routes. Requires
// Next.js >= 16.2.0-canary.48 (we're on 16.2.2). The builder itself
// branches on phase (development vs build) so this is safe for prod.
export default withSentryConfig(
  withWorkflow(nextConfig, { workflows: { lazyDiscovery: true } }),
  {
    // For all available options, see:
    // https://www.npmjs.com/package/@sentry/webpack-plugin#options

    org: SENTRY_ORG,
    project: SENTRY_PROJECT,
    release: SENTRY_RELEASE ? { name: SENTRY_RELEASE } : undefined,

    // Only print logs for uploading source maps in CI
    silent: !process.env.CI,

    // For all available options, see:
    // https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/

    // Upload a larger set of source maps for prettier stack traces (increases build time)
    widenClientFileUpload: true,

    // No-op: source map upload moved to sentry-upload Docker stage (KEEP-280).
    // Kept for safety in case SENTRY_AUTH_TOKEN is ever set during build.
    sourcemaps: {
      deleteSourcemapsAfterUpload: true,
    },

    // Route browser requests to Sentry through a Next.js rewrite to circumvent ad-blockers.
    // This can increase your server load as well as your hosting bill.
    // Note: Check that the configured route will not match with your Next.js middleware, otherwise reporting of client-
    // side errors will fail.
    tunnelRoute: "/monitoring",

    webpack: {
      treeshake: {
        removeDebugLogging: true,
      },
    },
  }
);
