/**
 * Chain-scoped test data for protocol-coverage fixtures (KEEP-458).
 *
 * Authoritative for: known testnet tokens, faucet contracts. The persistent
 * E2E test user's wallet address is NOT here -- KEEP-529 made it
 * HSM-generated by Turnkey, so the address differs per environment. Callers
 * look it up from `organization_wallets` at test/seed time and pass it into
 * the builders in `lib/test-data/build-workflow.ts`.
 *
 * Where addresses come from:
 *   - Tokens are extracted/extended from `scripts/seed/seed-tokens.ts` and from
 *     existing usage in `tests/integration/protocol-superfluid-onchain.test.ts`.
 *   - Aave V3 Sepolia faucet is from Aave's address book (verify against
 *     https://aave.com/docs/resources/addresses before relying on it).
 */

/** Env var name the funder script reads. The PK itself must never appear in code. */
export const TESTNET_FUNDER_PK_ENV = "TESTNET_FUNDER_PK";

export type TokenSymbol =
  | "WETH"
  | "USDC"
  | "USDT"
  | "DAI"
  | "USDS"
  | "FUSDC"
  | "FUSDCX";

export type TokenEntry = {
  address: string;
  decimals: number;
  symbol: TokenSymbol;
};

/**
 * Per-chain token address registry. Phase 1 only needs Sepolia entries
 * for aave-v3 (DAI test token) and superfluid (fUSDC + fUSDCx).
 * Extend per protocol as new chains come online.
 */
export const TOKEN_REGISTRY: Record<
  string /* chainId */,
  Partial<Record<TokenSymbol, TokenEntry>>
> = {
  // Ethereum Sepolia
  "11155111": {
    // Aave V3 Sepolia DAI test token (matches existing
    // scripts/seed/workflows/aave-v3/write-actions.json usage).
    DAI: {
      address: "0xFF34B3d4Aee8ddCd6F9AFFFB6Fe49bD371b8a357",
      decimals: 18,
      symbol: "DAI",
    },
    // Sepolia WETH (canonical Sepolia WETH).
    WETH: {
      address: "0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14",
      decimals: 18,
      symbol: "WETH",
    },
    // Superfluid fUSDC underlying ERC-20 (from protocol-superfluid-onchain.test.ts:52).
    FUSDC: {
      address: "0xe72f289584eDA2bE69Cfe487f4638F09bAc920Db",
      decimals: 18,
      symbol: "FUSDC",
    },
    // Superfluid fUSDCx SuperToken wrapper (from protocol-superfluid-onchain.test.ts:49).
    FUSDCX: {
      address: "0xb598E6C621618a9f63788816ffb50Ee2862D443B",
      decimals: 18,
      symbol: "FUSDCX",
    },
  },
};

/**
 * Faucet contract that mints a testnet token to a recipient.
 * Type kept for Phase 2 expansion; the generator does not consume FAUCETS in
 * Phase 1. ERC20 acquisition is verified-only via the TS preflight in
 * `tests/integration/protocol-coverage/_shared/funding.ts` (manual provisioning
 * required when balances are short). Once a faucet ABI is verified per
 * (chain, token) and added here, the generator will emit `web3/write-contract`
 * setup nodes that call it automatically.
 */
export type FaucetSpec = {
  contract: string;
  functionName: string;
  /** Full ABI JSON for the mint function, single-element array. */
  abi: string;
};

/** Phase 1: empty. See FaucetSpec comment for the Phase 2 contract. */
export const FAUCETS: Record<
  string /* chainId */,
  Partial<Record<TokenSymbol, FaucetSpec>>
> = {};

/** Native gas floor below which the funder must top up the test wallet. */
export const MIN_NATIVE_BALANCE_WEI_BY_CHAIN: Record<string, bigint> = {
  "11155111": BigInt("1000000000000000"), // 0.001 ETH
};

/** How much native to send when topping up. */
export const FUND_NATIVE_AMOUNT_WEI_BY_CHAIN: Record<string, bigint> = {
  "11155111": BigInt("2000000000000000"), // 0.002 ETH
};
