/**
 * Chain-scoped test data for protocol-coverage fixtures (KEEP-458).
 *
 * Authoritative for: known testnet tokens, faucet contracts. The persistent
 * E2E test user's wallet address is NOT here -- KEEP-529 made it
 * HSM-generated by Turnkey, so the address differs per environment. Callers
 * look it up from `organization_wallets` at test/seed time and pass it into
 * the builders in `lib/test-data/build-workflow.ts`.
 *
 * Where addresses come from:
 *   - Tokens are extracted/extended from `scripts/seed/seed-tokens.ts` and from
 *     existing usage in `tests/integration/protocol-superfluid-onchain.test.ts`.
 *   - Aave V3 Sepolia faucet is from Aave's address book (verify against
 *     https://aave.com/docs/resources/addresses before relying on it).
 */

/** Env var name the funder script reads. The PK itself must never appear in code. */
export const TESTNET_FUNDER_PK_ENV = "TESTNET_FUNDER_PK";

export type TokenSymbol =
  | "WETH"
  | "USDC"
  | "USDT"
  | "DAI"
  | "USDS"
  | "LINK"
  | "FUSDC"
  | "FUSDCX";

export type TokenEntry = {
  address: string;
  decimals: number;
  symbol: TokenSymbol;
};

/**
 * Per-chain token address registry. Phase 1 only needs Sepolia entries
 * for aave-v3 (DAI test token) and superfluid (fUSDC + fUSDCx).
 * Extend per protocol as new chains come online.
 */
export const TOKEN_REGISTRY: Record<
  string /* chainId */,
  Partial<Record<TokenSymbol, TokenEntry>>
> = {
  // Ethereum Sepolia
  "11155111": {
    // Aave V3 Sepolia DAI test token (matches existing
    // scripts/seed/workflows/aave-v3/write-actions.json usage).
    DAI: {
      address: "0xFF34B3d4Aee8ddCd6F9AFFFB6Fe49bD371b8a357",
      decimals: 18,
      symbol: "DAI",
    },
    // Sepolia WETH (canonical Sepolia WETH).
    WETH: {
      address: "0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14",
      decimals: 18,
      symbol: "WETH",
    },
    // Aave V3 Sepolia LINK test token. Selected over DAI because Aave's
    // DAI/USDC/USDT reserves on Sepolia hit `SUPPLY_CAP_EXCEEDED` (error 51);
    // LINK has headroom and is borrowable. Verified 2026-05-12 via eth_call.
    LINK: {
      address: "0xf8Fb3713D459D7C1018BD0A49D19b4C44290EBE5",
      decimals: 18,
      symbol: "LINK",
    },
    // Superfluid fUSDC underlying ERC-20 (from protocol-superfluid-onchain.test.ts:52).
    FUSDC: {
      address: "0xe72f289584eDA2bE69Cfe487f4638F09bAc920Db",
      decimals: 18,
      symbol: "FUSDC",
    },
    // Superfluid fUSDCx SuperToken wrapper (from protocol-superfluid-onchain.test.ts:49).
    FUSDCX: {
      address: "0xb598E6C621618a9f63788816ffb50Ee2862D443B",
      decimals: 18,
      symbol: "FUSDCX",
    },
  },
};

/** Faucet contract that mints a testnet token to a recipient. */
export type FaucetSpec = {
  contract: string;
  functionName: string;
  /** Full ABI JSON for the mint function, single-element array. */
  abi: string;
};

/**
 * Faucet registry consumed by `tests/e2e/vitest/protocol-coverage/_shared/funding.ts`.
 * The TS preflight calls each faucet from the funder EOA before the setup
 * workflow runs. Args are bound by input *name* (case-insensitive):
 *   `token` -> token's address on this chain
 *   `to` / `recipient` -> the test wallet address
 *   `amount` / `value` -> requiredTokens[i].human in wei (using token decimals)
 */
export const FAUCETS: Record<
  string /* chainId */,
  Partial<Record<TokenSymbol, FaucetSpec>>
> = {
  "11155111": {
    // Aave V3 Sepolia faucet: mints any Aave testnet reserve token.
    // Verified contract exists at this address (eth_getCode).
    LINK: {
      contract: "0xC959483DBa39aa9E78757139af0e9a2EDEb3f42D",
      functionName: "mint",
      abi: JSON.stringify([
        {
          type: "function",
          name: "mint",
          stateMutability: "nonpayable",
          inputs: [
            { name: "token", type: "address" },
            { name: "to", type: "address" },
            { name: "amount", type: "uint256" },
          ],
          outputs: [{ name: "", type: "uint256" }],
        },
      ]),
    },
    // FUSDC exposes a permissionless `mint(to, amount)` on its own ERC20.
    // Verified by inspecting bytecode (selector 0x40c10f19 present).
    FUSDC: {
      contract: "0xe72f289584eDA2bE69Cfe487f4638F09bAc920Db",
      functionName: "mint",
      abi: JSON.stringify([
        {
          type: "function",
          name: "mint",
          stateMutability: "nonpayable",
          inputs: [
            { name: "to", type: "address" },
            { name: "amount", type: "uint256" },
          ],
          outputs: [],
        },
      ]),
    },
  },
};

/** Native gas floor below which the funder must top up the test wallet. */
export const MIN_NATIVE_BALANCE_WEI_BY_CHAIN: Record<string, bigint> = {
  "11155111": BigInt("1000000000000000"), // 0.001 ETH
};

/** How much native to send when topping up. */
export const FUND_NATIVE_AMOUNT_WEI_BY_CHAIN: Record<string, bigint> = {
  "11155111": BigInt("2000000000000000"), // 0.002 ETH
};
