/**
 * Protocol Definitions Index (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * Imports all protocol definitions and registers them at import time.
 * This ensures the protocol registry is populated when the Next.js
 * server starts (via the plugin import chain).
 *
 * Registered protocols: aave-v3, aave-v4, aerodrome, ajna, chainlink, chronicle, compound-v3, cowswap, curve, ethena, frax-ether-v2, hyperliquid, lido, morpho, pendle, rocket-pool, safe, sky, spark, superfluid, uniswap-v3, wrapped, yearn-v3
 */

import { protocolToPlugin, registerProtocol } from "@/lib/protocol-registry";
import { registerIntegration } from "@/plugins/registry-core";

import aaveV3Def from "./aave-v3";
import aaveV4Def from "./aave-v4";
import aerodromeDef from "./aerodrome";
import ajnaDef from "./ajna";
import chainlinkDef from "./chainlink";
import chronicleDef from "./chronicle";
import compoundV3Def from "./compound-v3";
import cowswapDef from "./cowswap";
import curveDef from "./curve";
import ethenaDef from "./ethena";
import fraxEtherV2Def from "./frax-ether-v2";
import hyperliquidDef from "./hyperliquid";
import lidoDef from "./lido";
import morphoDef from "./morpho";
import pendleDef from "./pendle";
import rocketPoolDef from "./rocket-pool";
import safeDef from "./safe";
import skyDef from "./sky";
import sparkDef from "./spark";
import superfluidDef from "./superfluid";
import uniswapV3Def from "./uniswap-v3";
import wrappedDef from "./wrapped";
import yarnV3Def from "./yearn-v3";

registerProtocol(aaveV3Def);
registerIntegration(protocolToPlugin(aaveV3Def));
registerProtocol(aaveV4Def);
registerIntegration(protocolToPlugin(aaveV4Def));
registerProtocol(aerodromeDef);
registerIntegration(protocolToPlugin(aerodromeDef));
registerProtocol(ajnaDef);
registerIntegration(protocolToPlugin(ajnaDef));
registerProtocol(chainlinkDef);
registerIntegration(protocolToPlugin(chainlinkDef));
registerProtocol(chronicleDef);
registerIntegration(protocolToPlugin(chronicleDef));
registerProtocol(compoundV3Def);
registerIntegration(protocolToPlugin(compoundV3Def));
registerProtocol(cowswapDef);
registerIntegration(protocolToPlugin(cowswapDef));
registerProtocol(curveDef);
registerIntegration(protocolToPlugin(curveDef));
registerProtocol(ethenaDef);
registerIntegration(protocolToPlugin(ethenaDef));
registerProtocol(fraxEtherV2Def);
registerIntegration(protocolToPlugin(fraxEtherV2Def));
registerProtocol(hyperliquidDef);
registerProtocol(lidoDef);
registerIntegration(protocolToPlugin(lidoDef));
registerProtocol(morphoDef);
registerIntegration(protocolToPlugin(morphoDef));
registerProtocol(pendleDef);
registerIntegration(protocolToPlugin(pendleDef));
registerProtocol(rocketPoolDef);
registerIntegration(protocolToPlugin(rocketPoolDef));
registerProtocol(safeDef);
registerIntegration(protocolToPlugin(safeDef));
registerProtocol(skyDef);
registerIntegration(protocolToPlugin(skyDef));
registerProtocol(sparkDef);
registerIntegration(protocolToPlugin(sparkDef));
registerProtocol(superfluidDef);
registerIntegration(protocolToPlugin(superfluidDef));
registerProtocol(uniswapV3Def);
registerIntegration(protocolToPlugin(uniswapV3Def));
registerProtocol(wrappedDef);
registerIntegration(protocolToPlugin(wrappedDef));
registerProtocol(yarnV3Def);
registerIntegration(protocolToPlugin(yarnV3Def));
